FROM osrf/ros:noetic-desktop-full


# Dependencies we use, catkin tools is very good build system
# https://github.com/ethz-asl/kalibr/wiki/installation
RUN apt-get update && DEBIAN_FRONTEND=noninteractive \
	apt-get install -y \
	git wget autoconf automake nano \
	python3-dev python3-pip python3-scipy python3-matplotlib \
	ipython3 python3-wxgtk4.0 python3-tk python3-igraph python3-pyx \
	libeigen3-dev libboost-all-dev libsuitesparse-dev \
	doxygen \
	libopencv-dev \
	libpoco-dev libtbb-dev libblas-dev liblapack-dev libv4l-dev \
	python3-catkin-tools python3-osrf-pycommon

# ---- Workspace ----
ENV WORKSPACE=/catkin_ws

RUN mkdir -p $WORKSPACE/src

# Initialize catkin workspace
RUN /bin/bash -c "source /opt/ros/noetic/setup.bash && \
    cd $WORKSPACE && \
    catkin init && \
    catkin config --extend /opt/ros/noetic && \
    catkin config --cmake-args -DCMAKE_BUILD_TYPE=Release"

# (Optional) Add kalibr source
# ADD . $WORKSPACE/src/kalibr

# ---- Python tools ----
RUN pip3 install rosbags

# ---- Bash aliases ----
RUN echo "alias build_ws='catkin build --workspace $WORKSPACE -j\$(nproc) --force-cmake'" >> /root/.bashrc && \
    echo "alias rebuild_ws='catkin clean -y --workspace $WORKSPACE && catkin build --workspace $WORKSPACE -j\$(nproc)'" >> /root/.bashrc

# ---- Environment setup ----
RUN echo "source /opt/ros/noetic/setup.bash" >> /root/.bashrc && \
    echo "if [ -f $WORKSPACE/devel/setup.bash ]; then source $WORKSPACE/devel/setup.bash; fi" >> /root/.bashrc && \
    echo "export KALIBR_MANUAL_FOCAL_LENGTH_INIT=1" >> /root/.bashrc

# ---- Default shell ----
WORKDIR $WORKSPACE
CMD ["/bin/bash"]