#Accelerometers
accelerometer_noise_density: 1.0e-02   #Noise density (continuous-time)
accelerometer_random_walk:   2.0e-03   #Bias random walk

#Gyroscopes
gyroscope_noise_density:     1.0e-03   #Noise density (continuous-time)
gyroscope_random_walk:       2.0e-04   #Bias random walk

rostopic:                    /ouster_lidar/imu      #the IMU ROS topic
update_rate:                 10.0      #Hz (for discretization of the values above)